name: cron-new-stories
on:
  schedule:
    - cron: '* 16 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: | 
          curl --request POST --url 'https://story-typer.vercel.app/api/update' --header 'Authorization: Bearer ${{ process.env.API_ACCESS_TOKEN }}'