name: cron-new-stories
on:
  schedule:
    - cron: '40 10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: | 
          curl --request POST \ 
          --url 'https://storytyper.stevenwebster.co/api/update' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'